version: '3.8'

services:
  mongodb:
    image: mongo:8
    container_name: ${MONGO_DATABASE_NAME}
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MOGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MOGO_ADMIN_PASSWORD}
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - ./mongo-data:/data/db
volumes:
  mongo_data: